version: '4.8'
services:
  postgres:
    image: 'postgres:13.1-alpine'
    restart: always
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=vaadinstart
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./dataset:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: my-app2
    depends_on:
      - postgres
    ports:
      - 8080:8080
    expose:
      - 9090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vaadinstart
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
